server {
    listen 80;
    server_name 123.56.156.79;

    root /var/www/mood_guardian/frontend/dist;
    index index.html;

    # 通用代理请求头，供下方所有反代 location 继承
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8000;
    }

    location /docs {
        proxy_pass http://127.0.0.1:8000;
    }

    location /static/ {
        proxy_pass http://127.0.0.1:8000;
    }
}
